//******************************************************************************************************
//  Startup.cs - Gbtc
//
//  Copyright © 2026, Grid Protection Alliance.  All Rights Reserved.
//
//  Licensed to the Grid Protection Alliance (GPA) under one or more contributor license agreements. See
//  the NOTICE file distributed with this work for additional information regarding copyright ownership.
//  The GPA licenses this file to you under the Eclipse Public License -v 1.0 (the "License"); you may
//  not use this file except in compliance with the License. You may obtain a copy of the License at:
//
//      http://www.opensource.org/licenses/eclipse-1.0.php
//
//  Unless agreed to in writing, the subject software distributed under the License is distributed on an
//  "AS-IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. Refer to the
//  License for the specific language governing permissions and limitations.
//
//  Code Modification History:
//  ----------------------------------------------------------------------------------------------------
//  06/01/2026 - Marcos Vinicius Snak
//       Generated original version of source code.
//  06/05/2026 - Marcos Vinicius Snak
//       Added FileUploadOperationFilter to enable file picker on /import endpoint in Swagger UI.
//       Added XML documentation comments to Swagger via IncludeXmlComments.
//  09/02/2026 - Eduardo Oliveira
//       Copilot Review follow-up: added ConfigureHttpListenerAuthentication, which wires
//       ServiceHost.SelectAuthenticationScheme into the OWIN host's underlying HttpListener so
//       AuthenticationSchemes/AnonymousResourceExpression are actually enforced instead of being read
//       and ignored.
//
//******************************************************************************************************

using Newtonsoft.Json.Converters;
using Owin;
using StreamSplitter.Api.Filters;
using Swashbuckle.Application;
using System;
using System.IO;
using System.Net;
using System.Web.Http;

namespace StreamSplitter.Api
{
    /// <summary>
    /// OWIN startup class for the Stream Splitter Web API. Configures attribute routing, JSON
    /// serialization, Swagger UI, and the Web API middleware.
    /// </summary>
    /// <remarks>
    /// This class is passed directly to <c>WebApp.Start&lt;Startup&gt;()</c> in <see
    /// cref="StreamSplitter.ServiceHost"/> — the <c>[assembly: OwinStartup]</c> auto-discovery
    /// attribute is intentionally omitted.
    /// </remarks>
    public class Startup
    {
        #region [ Methods ]

        /// <summary>
        /// Configures the OWIN middleware pipeline.
        /// </summary>
        /// <param name="app">The <see cref="IAppBuilder"/> instance to configure.</param>
        public void Configuration(IAppBuilder app)
        {
            ConfigureHttpListenerAuthentication(app);

            HttpConfiguration config = new HttpConfiguration();

            // Enable attribute-based routing ([RoutePrefix] / [Route] on controllers)
            config.MapHttpAttributeRoutes();

            // Serialize enum values as strings for readability in JSON responses
            config.Formatters.JsonFormatter.SerializerSettings.Converters
                .Add(new StringEnumConverter());

            // Remove XML formatter — this API speaks JSON only
            config.Formatters.Remove(config.Formatters.XmlFormatter);

            // Configure Swashbuckle: single API version, enums as strings in schema
            config
                .EnableSwagger(c =>
                {
                    c.SingleApiVersion("v1", "Stream Splitter API");
                    c.DescribeAllEnumsAsStrings();
                    c.OperationFilter<FileUploadOperationFilter>();

                    // Load XML documentation generated by the C# compiler so that controller
                    // summaries, parameter descriptions, and remarks with examples are displayed in
                    // the Swagger UI.
                    string xmlPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "StreamSplitter.xml");

                    if (File.Exists(xmlPath))
                        c.IncludeXmlComments(xmlPath);
                })
                .EnableSwaggerUi();

            app.UseWebApi(config);
        }

        /// <summary>
        /// Wires <see cref="StreamSplitter.ServiceHost.SelectAuthenticationScheme"/> into the OWIN
        /// host's underlying <see cref="HttpListener"/> so <c>AuthenticationSchemes</c> and
        /// <c>AnonymousResourceExpression</c> are enforced by the listener itself, ahead of the Web
        /// API pipeline, instead of only being validated at startup.
        /// </summary>
        /// <param name="app">The <see cref="IAppBuilder"/> instance being configured.</param>
        /// <remarks>
        /// Katana's <c>Microsoft.Owin.Host.HttpListener</c> exposes the listener under this
        /// well-known property key before <see cref="Configuration"/> runs. If the host is not
        /// backed by <see cref="HttpListener"/> (e.g. a different OWIN server), authentication is
        /// left unconfigured and the API remains anonymous, matching prior behavior.
        /// </remarks>
        private static void ConfigureHttpListenerAuthentication(IAppBuilder app)
        {
            if (!app.Properties.TryGetValue("System.Net.HttpListener", out object listenerProperty) || listenerProperty is not HttpListener listener)
                return;

            // Fallback used only if AuthenticationSchemeSelectorDelegate throws for a given request.
            listener.AuthenticationSchemes = AuthenticationSchemes.Anonymous;

            listener.AuthenticationSchemeSelectorDelegate = request =>
                StreamSplitter.ServiceHost.SelectAuthenticationScheme(
                    request.Url?.AbsolutePath,
                    StreamSplitter.ServiceHost.WebApiAnonymousResourcePattern,
                    StreamSplitter.ServiceHost.WebApiAuthenticationSchemes);
        }

        #endregion [ Methods ]
    }
}